# Generated by Django 5.2.17 on 2026-09-17 06:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400)),
                ('answer', models.TextField()),
                ('provider', models.CharField(default='local', max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=60)),
                ('grounded', models.BooleanField(default=True, help_text='False when the answer had to fall back to generic guidance.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_exchanges', to='properties.listing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_exchanges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='MarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=80)),
                ('listing_count', models.PositiveIntegerField(default=0)),
                ('median_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('median_price_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_listings', models.PositiveIntegerField(default=0)),
                ('trade_volume', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
            ],
            options={
                'ordering': ('-date', 'city'),
                'constraints': [models.UniqueConstraint(fields=('date', 'city'), name='unique_snapshot_per_city_per_day')],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, help_text='0 is clean, 100 is unacceptable.')),
                ('band', models.CharField(choices=[('low', 'Low risk'), ('moderate', 'Moderate risk'), ('elevated', 'Elevated risk'), ('high', 'High risk')], default='moderate', max_length=10)),
                ('factors', models.JSONField(blank=True, default=list)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk', to='properties.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('low', models.DecimalField(decimal_places=2, max_digits=14)),
                ('high', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='low', max_length=10)),
                ('comparable_count', models.PositiveSmallIntegerField(default=0)),
                ('comparables', models.JSONField(blank=True, default=list)),
                ('adjustments', models.JSONField(blank=True, default=list)),
                ('narrative', models.TextField(blank=True, help_text='Plain-language explanation, written by the LLM layer.')),
                ('provider', models.CharField(default='local', max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='properties.listing')),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
                'indexes': [models.Index(fields=['listing', '-created_at'], name='intelligenc_listing_947fc6_idx')],
            },
        ),
    ]
