# Generated by Django 5.2.17 on 2026-09-17 06:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('shares', models.PositiveIntegerField(default=0, help_text='Non-zero when the offer is for a fraction, not the whole.')),
                ('message', models.CharField(blank=True, max_length=400)),
                ('status', models.CharField(choices=[('pending', 'Awaiting seller'), ('countered', 'Countered'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='pending', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_made', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='properties.listing')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OfferEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('opened', 'Offer made'), ('counter', 'Counter offer'), ('message', 'Message'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], max_length=12)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('body', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='market.offer')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('primary', 'Primary issue'), ('secondary', 'Secondary sale')], default='primary', max_length=10)),
                ('shares', models.PositiveIntegerField()),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='properties.listing')),
                ('seller', models.ForeignKey(blank=True, help_text='Empty on a primary issue, where shares come from the pool.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('buy', 'Purchase'), ('sell', 'Sale'), ('payout', 'Payout'), ('fee', 'Platform fee')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Negative when money leaves.', max_digits=14)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='market.trade')),
            ],
            options={
                'verbose_name_plural': 'ledger entries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.PositiveIntegerField(default=0)),
                ('invested', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total rupees paid in, used as the cost basis.', max_digits=14)),
                ('first_bought_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='properties.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'listing'), name='unique_holding_per_listing')],
            },
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['listing', 'status'], name='market_offe_listing_887add_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['buyer', '-created_at'], name='market_offe_buyer_i_a06486_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['listing', '-created_at'], name='market_trad_listing_bc264f_idx'),
        ),
    ]
