# Generated by Django 5.2.17 on 2026-09-17 06:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('headline', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True, max_length=600)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('wallet_address', models.CharField(blank=True, max_length=64)),
                ('wallet_verified_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_status', models.CharField(choices=[('not_started', 'Not started'), ('submitted', 'Submitted'), ('in_review', 'In review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_started', max_length=16)),
                ('kyc_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_notes', models.CharField(blank=True, max_length=300)),
                ('currency', models.CharField(choices=[('INR', 'Indian rupee'), ('USD', 'US dollar')], default='INR', max_length=3)),
                ('theme', models.CharField(choices=[('system', 'Match system'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=8)),
                ('notify_offers', models.BooleanField(default=True)),
                ('notify_watchlist', models.BooleanField(default=True)),
                ('notify_digest', models.BooleanField(default=True)),
                ('onboarding_dismissed', models.BooleanField(default=False)),
                ('last_seen_feed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pan', 'PAN card'), ('aadhaar', 'Aadhaar'), ('passport', 'Passport'), ('dl', 'Driving licence')], max_length=12)),
                ('file', models.FileField(upload_to='kyc/')),
                ('number_last4', models.CharField(blank=True, max_length=4)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_documents', to='accounts.profile')),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('offer', 'Offer'), ('listing', 'Listing'), ('watchlist', 'Watchlist'), ('search', 'Saved search'), ('kyc', 'Identity'), ('portfolio', 'Portfolio'), ('system', 'System')], default='system', max_length=12)),
                ('title', models.CharField(max_length=140)),
                ('body', models.CharField(blank=True, max_length=300)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'read_at'], name='accounts_no_user_id_780bd6_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('query', models.JSONField(default=dict, help_text='The filter set, as submitted.')),
                ('alerts_enabled', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_match_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_saved_search_name_per_user')],
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at_add', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='properties.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'listing'), name='unique_watchlist_entry')],
            },
        ),
    ]
