# Generated by Django 5.2.17 on 2026-09-17 06:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('icon', models.CharField(default='check', help_text='Symbol id in static/icons/sprite.svg, without the i- prefix.', max_length=40)),
            ],
            options={
                'verbose_name_plural': 'amenities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('summary', models.CharField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('property_type', models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('plot', 'Plot'), ('commercial', 'Commercial'), ('retail', 'Retail'), ('warehouse', 'Warehouse'), ('farmland', 'Farmland')], max_length=20)),
                ('ownership_type', models.CharField(blank=True, choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold'), ('cooperative', 'Co-operative society'), ('poa', 'Power of attorney')], max_length=20)),
                ('furnishing', models.CharField(blank=True, choices=[('unfurnished', 'Unfurnished'), ('semi', 'Semi furnished'), ('full', 'Fully furnished')], max_length=20)),
                ('facing', models.CharField(blank=True, choices=[('N', 'North'), ('NE', 'North east'), ('E', 'East'), ('SE', 'South east'), ('S', 'South'), ('SW', 'South west'), ('W', 'West'), ('NW', 'North west')], max_length=2)),
                ('address_line', models.CharField(blank=True, max_length=200)),
                ('locality', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, db_index=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('carpet_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('floor', models.SmallIntegerField(blank=True, null=True)),
                ('total_floors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('asking_price', models.DecimalField(blank=True, decimal_places=2, help_text='Rupees.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('price_negotiable', models.BooleanField(default=True)),
                ('fractional_enabled', models.BooleanField(default=False)),
                ('total_shares', models.PositiveIntegerField(default=0, help_text='Shares minted when fractional ownership is enabled.')),
                ('shares_sold', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('verified', 'Verified'), ('tokenized', 'Tokenized'), ('listed', 'Listed'), ('under_offer', 'Under offer'), ('sold', 'Sold'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=300)),
                ('wizard_step', models.PositiveSmallIntegerField(default=1, help_text='Furthest step completed, so a draft can be resumed.')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='listings', to='properties.amenity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ListingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('title_deed', 'Title deed'), ('tax_receipt', 'Property tax receipt'), ('utility_bill', 'Utility bill'), ('encumbrance', 'Encumbrance certificate'), ('approval', 'Building approval'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='listings/documents/')),
                ('original_name', models.CharField(blank=True, max_length=180)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, db_index=True, help_text='SHA-256 of the file, used to spot the same document reused across listings.', max_length=64)),
                ('verification', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('flagged', 'Flagged'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('verification_notes', models.JSONField(blank=True, default=list)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.listing')),
            ],
            options={
                'ordering': ('kind', '-uploaded_at'),
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/photos/')),
                ('thumbnail', models.ImageField(blank=True, editable=False, upload_to='listings/thumbs/')),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('width', models.PositiveIntegerField(default=0, editable=False)),
                ('height', models.PositiveIntegerField(default=0, editable=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.listing')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PricePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='properties.listing')),
            ],
            options={
                'ordering': ('recorded_at',),
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', '-published_at'], name='properties__status_adf09a_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city', 'property_type'], name='properties__city_057176_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['asking_price'], name='properties__asking__7250ed_idx'),
        ),
    ]
