# Generated by Django 5.2.17 on 2026-09-17 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='valuation_confidence',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='valuation_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['valuation_estimate'], name='properties__valuati_815371_idx'),
        ),
    ]
