# Generated by Django 5.2.17 on 2026-10-03 20:24

import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_listing_valuation_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingdocument',
            name='file',
            field=models.FileField(storage=properties.models.document_storage, upload_to='listings/documents/'),
        ),
    ]
