# Generated by Django 5.2.17 on 2026-09-17 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('metadata', 'Metadata'), ('image', 'Image'), ('document', 'Document')], max_length=10)),
                ('cid', models.CharField(db_index=True, max_length=120)),
                ('label', models.CharField(blank=True, max_length=140)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('provider', models.CharField(default='pinata', max_length=20)),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='properties.listing')),
            ],
            options={
                'ordering': ('-pinned_at',),
            },
        ),
        migrations.CreateModel(
            name='TokenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=60)),
                ('contract_address', models.CharField(blank=True, max_length=64)),
                ('chain', models.CharField(choices=[('polygon-amoy', 'Polygon Amoy'), ('sepolia', 'Ethereum Sepolia'), ('local', 'Local registry')], default='local', max_length=20)),
                ('tx_hash', models.CharField(blank=True, max_length=80)),
                ('metadata_cid', models.CharField(blank=True, max_length=120)),
                ('minted_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='properties.listing')),
            ],
        ),
    ]
