# Generated by Django 5.2.17 on 2026-09-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenrecord',
            name='block_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenrecord',
            name='chain_token_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenrecord',
            name='evidence_hash',
            field=models.CharField(blank=True, max_length=66),
        ),
        migrations.AddField(
            model_name='tokenrecord',
            name='recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenrecord',
            name='shares_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
