# Generated by Django 5.2.17 on 2026-09-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0002_onchain_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenrecord',
            name='chain',
            field=models.CharField(choices=[('polygon-amoy', 'Polygon Amoy'), ('sepolia', 'Ethereum Sepolia'), ('other', 'Development chain'), ('local', 'Local registry')], default='local', max_length=20),
        ),
    ]
